site_name: AusTrakka NAT Bioinformatics Methods Documentation
site_url: https://austrakka-nat.github.io/Bioinformatics-methods/

nav:
  - About: index.md
  - SE surveillance: se_surveillance.md
theme:
  name: material
  logo: images/logo.jpg
  palette:
      primary: blue grey
  icon:
      repo: fontawesome/brands/github-alt
  
repo_url: https://github.com/AusTrakka-NAT/Bioinformatics-methods
repo_name: AusTrakka-NAT/Bioinformatics-methods
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/AusTrakka-NAT/Bioinformatics-methods

markdown_extensions:
  - attr_list
  