site_name: AusTrakka NAT Bioinformatics Methods Documentation
site_url: https://austrakka-nat.github.io/Bioinformatics-methods/

nav:
  - About: index.md
  - SE surveillance: se_surveillance.md
theme:
  name: material
  logo: images/logo.svg
  palette:
      primary: blue grey
  icon:
      repo: fontawesome/brands/github-alt
  
features:
    - content.code.copy
    - content.code.select

  repo_url: https://github.com/AusTrakka-NAT/Bioinformatics-methods
  repo_name: AusTrakka-NAT/Bioinformatics-methods
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/AusTrakka-NAT/Bioinformatics-methods

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format